title:              LunaLunaఇ
email:              ww0111@naver.com
description:        내맘대로 쓰는 개발일기
author:             Seoyoung Lee
baseurl:            ""  #'/'로 끝나야함
url:                "https://seoyoung2.github.io"

# Social Profiles
github_username:    Seoyoung2
facebook_username:  seoyoung.lee.1291
instagram_username:  twowestzero

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-161582913-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache