title:              My Blog
email:              ww0111@naver.com
description:        아직 준비중입니당
author:             Seoyoung Lee
baseurl:            ""
url:                "https://seoyoung2.github.io"

# Social Profiles
github_username:    Seoyoung2
facebook_username:  seoyoung.lee.1291
instagram_username:  twowestzero

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
